# Generated by Django 5.1.2 on 2025-01-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QABlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=65535)),
                ('reply', models.CharField(max_length=65535)),
                ('comment', models.CharField(max_length=65535)),
                ('question_type', models.CharField(max_length=65535)),
                ('userID', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
