# Generated by Django 5.1.2 on 2025-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='answer',
            field=models.CharField(default=None, max_length=65535),
        ),
    ]
