# Generated by Django 5.1.2 on 2025-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tasks_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='answer',
            field=models.CharField(default=None, max_length=65535, null=True),
        ),
    ]
