# Generated by Django 5.1.2 on 2025-03-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tasks_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_blocks', models.JSONField()),
                ('userID', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='QABlock',
        ),
    ]
